#ifndef CONSTANTS_H
#define CONSTANTS_H

#undef DEBUG

// OS CONFIGURATION
#define OS_DELAY 1
#define BUFFER_SIZE 256
#define MAIN_TASK_SIZE 1024
#define TASKS_SIZES 1024
#define TASKS_SIZES_EXPLORER 4096
#define RX_COMMAND_BUFFER_SIZE 700

// GAME INFORMATIONS
#define MAX_PLANETS_NUMBER 8
#define SHIPS_NUMBER 9
#define NUMBER_OF_TEAM 4
#define BASE_NUMBER 1
#define NUMBER_OF_GAME_DATA 1

// PARSING DELIMITER
#define SERVER_RESPONSE_DELIMITER ","
#define SERVER_RESPONSE_PLANET_DELIMITER 'P'
#define SERVER_RESPONSE_SHIP_DELIMITER 'S'
#define SERVER_RESPONSE_BASE_DELIMITER 'B'

#endif // CONSTANTS_H